# Generated by Django 6.0.6 on 2026-07-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
